### ISSUE TITLE
Atom categories not returned

### ISSUE THREAD

**Issue by tcitworld** [michaelnisi/feeder#12]
Categories are not returned for an Atom feed.

Syntax is not the same:
```xml
<category term="my-tag" label="MyTag" />
```

**Comment by michaelnisi** [comment]
Thanks for your feedback, looking into it.

**Comment by michaelnisi** [comment]
Resolved with 29c5269fd0ffb1f5f504e038512e5aab

**Comment by tcitworld** [comment]
Thanks !
